### ISSUE TITLE
DbUpMigration - Better solution of getting DbUp NuGet package

### ISSUE THREAD

**Issue by johanclasson** [johanclasson/vso-agent-tasks#37]
1) Package DLL with task?
2) Get latest minor version?
3) Input field for version?

**Comment by AndersSahlin** [comment]
I've run into an issue with this recently. It seems that the latest recommended version of NuGet (4.6.2) i dependent on .NET 4.6.

Since this task is set to always use the latest NuGet.exe available a release can (and did) suddenly stop working if an environment does not meet the dependency requirements.

Proposed solution: Lock NuGet version to 4.5.1, or earlier?

**Comment by johanclasson** [comment]
Ok. Thanks for reporting this. Either your solution or perhaps stop downloading NuGet and instruct user to use [Microsofts NuGet Tool Installer](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/tool/nuget?view=vsts) instead. In the latter scenario, DbUp would of course need to be bundled with the DbUp migration-task so that we do not (intentially) break people's builds.

**Comment by johanclasson** [comment]
Let's do your solution now and we can think about something better in the long term.

It should be an easy fix changing the download URL for NuGet.

**Comment by johanclasson** [comment]
With the latest release (1.1.4) the task comes with a bundled version of DbUp, which will fix your issue since it will no longer be invoking NuGet.
