### ISSUE TITLE
folder selection question

### ISSUE THREAD

**Issue by mdugan2453** [johanclasson/vso-agent-tasks#40]
I am trying to select the folder where I have my script files in my database project.  the project folder layout looks different than what the VSTS folder popup will allow me to choose from - can't get to folder in my project where scripts are at.  I want to point to a sub folder under the Scripts folder.  thanks for any and all help Mike
![c2](https://user-images.githubusercontent.com/26255050/41432200-4c3829a6-6fe3-11e8-9553-ed5c8b362870.PNG)
![c1](https://user-images.githubusercontent.com/26255050/41432201-4c4c04b2-6fe3-11e8-920c-44aa25648687.PNG)

**Comment by johanclasson** [comment]
Hm... If your files are not there when you open the dialog with the [...]-button my guess is that there is something wrong in the release definition. It can be due to a number of reasons. There comes to mind:

* Perhaps you have not linked any build artifacts to your release?
* Perhaps your build does not publish the expected files into the artifact?
* Perhaps the linked build have never been run?

**Comment by johanclasson** [comment]
You do write "_project folder layout looks different than what the VSTS folder popup will allow me to choose from_" which would indicate that your do get some of your files, which in turn would indicate that the problem is actually in the build. Or have you perhaps not linked your release to a build and instead just grabbed the source code as an artifact in the release?

**Comment by mdugan2453** [comment]
got it/was mapping under build definition - all set!  thanks for the quick response
