### ISSUE TITLE
Issue on certain environments :"Format of the initialization string does not conform to specification starting at index 0." ---> System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0

### ISSUE THREAD

**Issue by teedor** [johanclasson/vso-agent-tasks#62]
Hi

I have a pipeline with 3 tasks. DEV and SYS work fine.

When I clone the task to our UAT environment I get this error:
Exception calling ".ctor" with "1" argument(s): "Format of the initialization string does not conform to specification starting at index 0." ---> System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0

I'm trying to figure out what could cause this exception. It must be a problem with our environments and not your code because is works on 3 out of 3 environments, but I was wondering if you might have an idea what could cause this. Initial googling pointed to discussions about the connection string (not related to dbup) but our connection string is fine because our dbup console application runs fine from visual studio against the same database as the one thats failing in the pipeline.

Thanks

**Comment by johanclasson** [comment]
Sorry, but I have no idea.

But you can diagnose the issue yourself by downloading [this folder](https://github.com/johanclasson/vso-agent-tasks/tree/master/DbUpMigration/task) to your environment and execute the powershell manually.

I suspect it is something with the [c# part in DatabaseWithDbUp.ps1](https://github.com/johanclasson/vso-agent-tasks/blob/master/DbUpMigration/task/Update-DatabaseWithDbUp.ps1#L31-L57) that fails. Perhaps is it because you have not got the .NET Core SDK installed on that machine?

**Comment by teedor** [comment]
Thank you very much for your reply. It was useful to see the powershell scripts but we were unable to fix the issue. My team has no control over these environments that were set up hundreds of years ago.

Managed to work around it by using your Azure DevOps extension on some environments and deploying and executing a console app on other environments.

**Comment by johanclasson** [comment]
Glad to hear that you got past the issue somehow. Thanks for the follow up!
