### ISSUE TITLE
!=Issue, how does it compare with RoundHouse?

### ISSUE THREAD

**Issue by rahulduggal18** [johanclasson/vso-agent-tasks#68]
Not really an issue in this, I'm trying to understand how it compares with RH(https://github.com/chucknorris/roundhouse).

RH is very portable and simple to use(just _rh.exe dbName_) while this one seems to have a lot of dependencies on DLL's, plus this ps1 is mostly just wrapping C# code in it.

On feature I think it has is "[variable substitution](https://dbup.readthedocs.io/en/latest/more-info/variable-substitution/)" which RH lacks.

_background is we have working RH set-up but someone suggested DbUp now in organisation. Thanks._

**Comment by johanclasson** [comment]
I have no first hand experience with Roundhouse, but I think it looks like a similar tool to what DbUp is. 

I think that what it boils down to is that Roundhouse is more of a concept, and that DbUp is more like a NuGet-library that you can use to build your flow just the way you want it. If you want a more in depth comparison between roundhouse and DbUp I suggest you go to [the DbUp-repo](https://github.com/DbUp/DbUp).

Roundhouse (or DbUp "naitive") does not seem to integrate well with Azure DevOps which is why I created this Azure DevOps extension.
